### ISSUE TITLE
Timed auto-mute.

### ISSUE THREAD

**Issue by sirocyl** [nh-server/Kurisu#218]
Stimulus: User sends _x_ messages within _y_ seconds.
Response: Kurisu mutes user according to procedure below:

First mute is 30 seconds; Subsequent re-mutes double the mute time, to a maximum of 64 minutes.
After the last mute, if the user is not muted again, mute counter resets after 24 hours.

**Comment by 916253** [comment]
Hey; sorry for taking such a long time to get to responding to this
 We've collectively decided against auto mute having a time-out by default, but in discussions about the topic discussed that it might make sense to at least do something to keep us aware of auto muted users:
 Instead of auto unmuting or sticking with the current implementation, ping the mods channel 30 minutes to an hour after the auto mute so that muted users aren't forgotten about. Since the message notifying staff of the auto mute happening doesn't actually ping anybody, just posts in `#mods`, the new idea would be to keep that initial no mention message, then later post a second message mentioning `@here`, reminding active staff that a user has been muted for a while, and allow staff to decide how to proceed from there.
